version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.9.29-management
    ports:
      - 5672:5672
      - 15672:15672
  node-express:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-nodejs-express
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq
