version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo
    logging:
      driver: none
    ports:
      - 27017:27017
  node-express:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-nodejs-express
    ports:
      - 3000:3000
    depends_on:
      - mongo
