### Users example call
GET http://localhost:3000/api/user

### Send message to producer
POST http://localhost:3000/api/user/create
content-type: application/json

{
    "message": "Creating first user!"
}